#!/usr/bin/Rscript

options(warn = -1)

args <- commandArgs(trailingOnly = TRUE)

getScriptPath <- function(){
    cmd.args <- commandArgs()
    m <- regexpr("(?<=^--file=).+", cmd.args, perl=TRUE)
    script.dir <- dirname(regmatches(cmd.args, m))
    if(length(script.dir) == 0) stop("can't determine script dir: please call the script with Rscript")
    if(length(script.dir) > 1) stop("can't determine script dir: more than one '--file' argument detected")
    return(script.dir)
}

if (file.exists(".Rprofile")) {
  source(".Rprofile")
}

d <- getScriptPath()

source(file.path(d, "R/repl.R"))
source(file.path(d, "R/ast.R"))
source(file.path(d, "R/evaluation.R"))
source(file.path(d, "R/core.R"))
source(file.path(d, "R/functions.R"))
source(file.path(d, "R/listprocessor.R"))
source(file.path(d, "R/types.R"))

if (length(args) == 0) {
  # repl mode
  slurp_repl()
} else {
  # source code mode
  source_slurp(args[[1]])
}
