#!/usr/bin/Rscript

options(warn = -1)

args <- commandArgs(trailingOnly = TRUE)

if (length(args) == 0) {
  # repl mode
  source("R/repl.R")
  repl()
} else {
  # source code mode
  source("R/ast.R")
  source("R/evaluation.R")
  source_code <- paste(readLines(args[[1]]), collapse = "\n")
  source_code <- stringr::str_remove_all(source_code, ";;.*")
  source_code <- stringi::stri_replace_all(source_code, regex = "\\s\\s\\s", " ")
  source_code <- stringr::str_match_all(source_code, "(\\(.*\\))")[[1]][,1]
  for (statement in source_code) {
    evaluate_ast(ast(statement))
  }
}
