#!/usr/bin/Rscript

options(warn = -1)

args <- commandArgs(trailingOnly = TRUE)

getScriptPath <- function(){
    cmd.args <- commandArgs()
    m <- regexpr("(?<=^--file=).+", cmd.args, perl=TRUE)
    script.dir <- dirname(regmatches(cmd.args, m))
    if(length(script.dir) == 0) stop("can't determine script dir: please call the script with Rscript")
    if(length(script.dir) > 1) stop("can't determine script dir: more than one '--file' argument detected")
    return(script.dir)
}

if (file.exists(".Rprofile")) {
  source(".Rprofile")
}

d <- getScriptPath()

source(file.path(d, "/R/repl.R"))
source(file.path(d, "R/ast.R"))
source(file.path(d, "R/evaluation.R"))
source(file.path(d, "R/core.R"))

if (length(args) == 0) {
  # repl mode
  repl()
} else {
  # source code mode
  source_code <- paste(readLines(args[[1]]), collapse = "\n")
  source_code <- strip_comments(source_code)
  source_code <- stringi::stri_replace_all(source_code, regex = "\\s\\s\\s", " ")
  source_code <- stringr::str_match_all(source_code, "(\\(.*\\))")[[1]][,1]
  for (statement in source_code) {
    evaluate_ast(ast(statement))
  }
}
